name: Hot_Shots
favicon: null
layout_spectrum: 0.05850419541820884
typography_spectrum: 0.17575759743340313
title: Team Page
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.23061563773080707
  lightness: 0.9139237119816244
  saturation: 0.6325140250846744
  rhythmicContrast: 0.7246989547275007
purpose: []
