name: Hot_Shots
favicon: null
layout_spectrum: 0.80215
typography_spectrum: 1
title: Team Page
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8a9168'
    - '#4e0c0d'
    - '#fa4a4c'
    - '#e4edfe'
    - '#e1b598'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.7246989547275007
purpose: []
